### ISSUE TITLE
AssertionError: The pathfile of KAIST dataset is not exist.

### ISSUE THREAD

**Issue by X-Ichigo** [lengmo1996/ECDM#2]
Missing logger folder: logs/2024-09-11T19-05-59_ecdm_first_stage/tensorboard
Traceback (most recent call last):
  File "/root/autodl-tmp/ECDM/main.py", line 139, in <module>
    cli_main()
  File "/root/autodl-tmp/ECDM/main.py", line 132, in cli_main
    cli = MyLightningCLI(
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 388, in __init__
    self._run_subcommand(self.subcommand)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 679, in _run_subcommand
    fn(**fn_kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 947, in _run
    self._data_connector.prepare_data()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 94, in prepare_data
    call._call_lightning_datamodule_hook(trainer, "prepare_data")
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/root/autodl-tmp/ECDM/ecdm/data/dataset.py", line 108, in prepare_data
    instantiate_from_config(data_cfg)
  File "/root/autodl-tmp/ECDM/ecdm/util.py", line 84, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/root/autodl-tmp/ECDM/ecdm/data/dataset.py", line 286, in __init__
    assert self.path.exists(), "The pathfile of KAIST dataset is not exist."
AssertionError: The pathfile of KAIST dataset is not exist.

**Comment by lengmo1996** [comment]
Please check the value of [data.init_args.train.root] in the config file. You need to modify these values to the corresponding paths.
