### ISSUE TITLE
How to use only one GPU

### ISSUE THREAD

**Issue by X-Ichigo** [lengmo1996/ECDM#3]

**Comment by lengmo1996** [comment]
The following command will train the model with one GPU:
python main.py fit -c configs/base_config.yaml -c configs/ecdm_first_stage.yaml --trainer.devices 0,

**Comment by X-Ichigo** [comment]
> The following command will train the model with one GPU: python main.py fit -c configs/base_config.yaml -c configs/ecdm_first_stage.yaml --trainer.devices 0,

**I try this, but get another error** 

Seed set to 23
ECDMFirstStage: Running in eps-prediction mode
DiffusionWrapper has 34.43 M params.
Keeping EMAs of 280.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py:126: `.fit(ckpt_path=None)` was called without a model. The last model of the previous `fit` call will be used. You can pass `fit(ckpt_path='best')` to use the best model or `fit(ckpt_path='last')` to use the last model. If you pass a value, this warning will be silenced.
/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py:186: .fit(ckpt_path="last") is set, but there is no last checkpoint available. No checkpoint will be loaded. HINT: Set `ModelCheckpoint(..., save_last=True)`.
You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[rank: 0] Seed set to 23
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

Missing logger folder: logs/2024-09-11T21-00-16_ecdm_first_stage/tensorboard
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type             | Params
-----------------------------------------------
0 | model     | DiffusionWrapper | 34.4 M
1 | model_ema | LitEma           | 0     
-----------------------------------------------
34.4 M    Trainable params
0         Non-trainable params
34.4 M    Total params
137.725   Total estimated model params size (MB)
Epoch 0:   0%|                                                                                                                                                               | 0/12025 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/autodl-tmp/ECDM/main.py", line 139, in <module>
    cli_main()
  File "/root/autodl-tmp/ECDM/main.py", line 132, in cli_main
    cli = MyLightningCLI(
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 388, in __init__
    self._run_subcommand(self.subcommand)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 679, in _run_subcommand
    fn(**fn_kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1033, in _run_stage
    self.fit_loop.run()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 212, in advance
    batch, _, __ = next(data_fetcher)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 78, in __next__
    out[i] = next(self.iterators[i])
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/ECDM/ecdm/data/dataset.py", line 54, in __getitem__
    return self.data[idx]
  File "/root/autodl-tmp/ECDM/ecdm/data/dataset.py", line 354, in __getitem__
    visible_HF_path = self.visible_HF_images[index]
IndexError: list index out of range

Epoch 0:   0%|          | 0/12025 [00:00<?, ?it/s]

**Comment by X-Ichigo** [comment]
> The following command will train the model with one GPU: python main.py fit -c configs/base_config.yaml -c configs/ecdm_first_stage.yaml --trainer.devices 0,


I try this, but get another error: 


Seed set to 23
ECDMFirstStage: Running in eps-prediction mode
DiffusionWrapper has 34.43 M params.
Keeping EMAs of 280.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py:126: `.fit(ckpt_path=None)` was called without a model. The last model of the previous `fit` call will be used. You can pass `fit(ckpt_path='best')` to use the best model or `fit(ckpt_path='last')` to use the last model. If you pass a value, this warning will be silenced.
/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py:186: .fit(ckpt_path="last") is set, but there is no last checkpoint available. No checkpoint will be loaded. HINT: Set `ModelCheckpoint(..., save_last=True)`.
You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[rank: 0] Seed set to 23
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

Missing logger folder: logs/2024-09-11T21-00-16_ecdm_first_stage/tensorboard
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type             | Params
-----------------------------------------------
0 | model     | DiffusionWrapper | 34.4 M
1 | model_ema | LitEma           | 0     
-----------------------------------------------
34.4 M    Trainable params
0         Non-trainable params
34.4 M    Total params
137.725   Total estimated model params size (MB)
Epoch 0:   0%|                                                                                                                                                               | 0/12025 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/autodl-tmp/ECDM/main.py", line 139, in <module>
    cli_main()
  File "/root/autodl-tmp/ECDM/main.py", line 132, in cli_main
    cli = MyLightningCLI(
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 388, in __init__
    self._run_subcommand(self.subcommand)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 679, in _run_subcommand
    fn(**fn_kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1033, in _run_stage
    self.fit_loop.run()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 212, in advance
    batch, _, __ = next(data_fetcher)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 78, in __next__
    out[i] = next(self.iterators[i])
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/ECDM/ecdm/data/dataset.py", line 54, in __getitem__
    return self.data[idx]
  File "/root/autodl-tmp/ECDM/ecdm/data/dataset.py", line 354, in __getitem__
    visible_HF_path = self.visible_HF_images[index]
IndexError: list index out of range

Epoch 0:   0%|          | 0/12025 [00:00<?, ?it/s]

**Comment by lengmo1996** [comment]
It seems an error about the dataloader. This error usually occurs when the dataset path is incorrectly configured and the images under the path cannot be loaded. I suggest checking if the data path is configured correctly or if the dataset structure is consistent with what we are using, as I am not sure if you are using a custom dataset.

**Comment by X-Ichigo** [comment]
> It seems an error about the dataloader. This error usually occurs when the dataset path is incorrectly configured and the images under the path cannot be loaded. I suggest checking if the data path is configured correctly or if the dataset structure is consistent with what we are using, as I am not sure if you are using a custom dataset.

In the ECDM/ecdm/data/dataset.py ：
line280：        edge_type="high_filter",
line296：        self.visible_HF_path = self.visible_all_path / ("train_" + self.edge_type)‘’

should change 'LLVIP/visible/train_HF'  to  'LLVIP/visible/train_high_filter'  ?

**Comment by lengmo1996** [comment]
> > It seems an error about the dataloader. This error usually occurs when the dataset path is incorrectly configured and the images under the path cannot be loaded. I suggest checking if the data path is configured correctly or if the dataset structure is consistent with what we are using, as I am not sure if you are using a custom dataset.
> 
> In the ECDM/ecdm/data/dataset.py ： line280： edge_type="high_filter", line296： self.visible_HF_path = self.visible_all_path / ("train_" + self.edge_type)‘’
> 
> should change 'LLVIP/visible/train_HF' to 'LLVIP/visible/train_high_filter' ?

Yes. We're sorry that we missed this during our code refactoring.

**Comment by lengmo1996** [comment]
> > It seems an error about the dataloader. This error usually occurs when the dataset path is incorrectly configured and the images under the path cannot be loaded. I suggest checking if the data path is configured correctly or if the dataset structure is consistent with what we are using, as I am not sure if you are using a custom dataset.
> 
> In the ECDM/ecdm/data/dataset.py ： line280： edge_type="high_filter", line296： self.visible_HF_path = self.visible_all_path / ("train_" + self.edge_type)‘’
> 
> should change 'LLVIP/visible/train_HF' to 'LLVIP/visible/train_high_filter' ?

The default edge type is 'high_filter' and it does not need to change. Can you debug it by some tools (like pycharm, vscode)? It may help to set a breakpoint at line 323 and inspect variables self.visible_HF_root_path and self.visible_HF_images.

**Comment by X-Ichigo** [comment]
> > > It seems an error about the dataloader. This error usually occurs when the dataset path is incorrectly configured and the images under the path cannot be loaded. I suggest checking if the data path is configured correctly or if the dataset structure is consistent with what we are using, as I am not sure if you are using a custom dataset.
> > 
> > 
> > In the ECDM/ecdm/data/dataset.py ： line280： edge_type="high_filter", line296： self.visible_HF_path = self.visible_all_path / ("train_" + self.edge_type)‘’
> > should change 'LLVIP/visible/train_HF' to 'LLVIP/visible/train_high_filter' ?
> 
> The default edge type is 'high_filter' and it does not need to change. Can you debug it by some tools (like pycharm, vscode)? It may help to set a breakpoint at line 323 and inspect variables self.visible_HF_root_path and self.visible_HF_images.

I have solved this issue，but meet another issue，the result tell me that the shape of the data which is send to self.diffusion_model is not suitable，however, I have change the dataset just like you provide.

the error information:

  File "/root/autodl-tmp/ECDM/ecdm/models/diffusion/ecdm_first_stage.py", line 729, in forward
    out = self.diffusion_model(xc, t)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/ECDM/ecdm/modules/diffusionmodules/simple_unet.py", line 298, in forward
    hs = [self.conv_in(x)]
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 6, 3, 3], expected input[1, 2, 512, 640] to have 6 channels, but got 2 channels instead
Epoch 0:   0%|          | 0/12025 [00:01<?, ?it/s]

**Comment by lengmo1996** [comment]
> > > > It seems an error about the dataloader. This error usually occurs when the dataset path is incorrectly configured and the images under the path cannot be loaded. I suggest checking if the data path is configured correctly or if the dataset structure is consistent with what we are using, as I am not sure if you are using a custom dataset.
> > > 
> > > 
> > > In the ECDM/ecdm/data/dataset.py ： line280： edge_type="high_filter", line296： self.visible_HF_path = self.visible_all_path / ("train_" + self.edge_type)‘’
> > > should change 'LLVIP/visible/train_HF' to 'LLVIP/visible/train_high_filter' ?
> > 
> > 
> > The default edge type is 'high_filter' and it does not need to change. Can you debug it by some tools (like pycharm, vscode)? It may help to set a breakpoint at line 323 and inspect variables self.visible_HF_root_path and self.visible_HF_images.
> 
> I have solved this issue，but meet another issue，the result tell me that the shape of the data which is send to self.diffusion_model is not suitable，however, I have change the dataset just like you provide.
> 
> the error information:
> 
> File "/root/autodl-tmp/ECDM/ecdm/models/diffusion/ecdm_first_stage.py", line 729, in forward out = self.diffusion_model(xc, t) File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/autodl-tmp/ECDM/ecdm/modules/diffusionmodules/simple_unet.py", line 298, in forward hs = [self.conv_in(x)] File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward return self._conv_forward(input, self.weight, self.bias) File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: Given groups=1, weight of size [128, 6, 3, 3], expected input[1, 2, 512, 640] to have 6 channels, but got 2 channels instead Epoch 0: 0%| | 0/12025 [00:01<?, ?it/s]

This is because of the inconsistency caused by the code refactoring before we open sourced it. You can either change the input channels from 6 to 2 or change the input image to a three-channel image. The former can be done by directly modifying the ecdm_first_stage.yaml configuration file, and the latter can be achieved through vis_img = vis_img.convert("RGB") in dataset.py 

More details can be seen in #1

**Comment by X-Ichigo** [comment]
> > > > > It seems an error about the dataloader. This error usually occurs when the dataset path is incorrectly configured and the images under the path cannot be loaded. I suggest checking if the data path is configured correctly or if the dataset structure is consistent with what we are using, as I am not sure if you are using a custom dataset.
> > > > 
> > > > 
> > > > In the ECDM/ecdm/data/dataset.py ： line280： edge_type="high_filter", line296： self.visible_HF_path = self.visible_all_path / ("train_" + self.edge_type)‘’
> > > > should change 'LLVIP/visible/train_HF' to 'LLVIP/visible/train_high_filter' ?
> > > 
> > > 
> > > The default edge type is 'high_filter' and it does not need to change. Can you debug it by some tools (like pycharm, vscode)? It may help to set a breakpoint at line 323 and inspect variables self.visible_HF_root_path and self.visible_HF_images.
> > 
> > 
> > I have solved this issue，but meet another issue，the result tell me that the shape of the data which is send to self.diffusion_model is not suitable，however, I have change the dataset just like you provide.
> > the error information:
> > File "/root/autodl-tmp/ECDM/ecdm/models/diffusion/ecdm_first_stage.py", line 729, in forward out = self.diffusion_model(xc, t) File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/autodl-tmp/ECDM/ecdm/modules/diffusionmodules/simple_unet.py", line 298, in forward hs = [self.conv_in(x)] File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward return self._conv_forward(input, self.weight, self.bias) File "/root/miniconda3/envs/ECDM/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: Given groups=1, weight of size [128, 6, 3, 3], expected input[1, 2, 512, 640] to have 6 channels, but got 2 channels instead Epoch 0: 0%| | 0/12025 [00:01<?, ?it/s]
> 
> This is because of the inconsistency caused by the code refactoring before we open sourced it. You can either change the input channels from 6 to 2 or change the input image to a three-channel image. The former can be done by directly modifying the ecdm_first_stage.yaml configuration file, and the latter can be achieved through vis_img = vis_img.convert("RGB") in dataset.py
> 
> More details can be seen in #1

thanks for your guidance
